### ISSUE TITLE
vs2012 update5 compiling errors

### ISSUE THREAD

**Issue by amir110** [oliora/samples#2]
hi
great sample.

when i add your header file to my project in vs2012 update5 i get bunch of errors.

`1>\spimpl.h(57): error C2873: 'type' : symbol cannot be used in a using-declaration
    1>          \spimpl.h(58) : see reference to class template instantiation 'spimpl::details::default_deleter<T>' being compiled
    1>\spimpl.h(57): error C2143: syntax error : missing ';' before '='
    1>\spimpl.h(57): error C2238: unexpected token(s) preceding ';'
    1>\spimpl.h(61): error C2988: unrecognizable template declaration/definition
    1>\spimpl.h(61): error C2059: syntax error : 'using'
    1>\spimpl.h(69): error C2988: unrecognizable template declaration/definition
    1>\spimpl.h(69): error C2059: syntax error : 'using'
    1>\spimpl.h(87): error C2873: 'pointer' : symbol cannot be used in a using-declaration
    1>          \spimpl.h(265) : see reference to class template instantiation 'spimpl::impl_ptr<T,Deleter,Copier>' being compiled
    1>\spimpl.h(87): error C2143: syntax error : missing ';' before '='
    1>\spimpl.h(87): error C2238: unexpected token(s) preceding ';'
    1>\spimpl.h(88): error C2873: 'element_type' : symbol cannot be used in a using-declaration
    1>\spimpl.h(88): error C2143: syntax error : missing ';' before '='
    1>\spimpl.h(88): error C2238: unexpected token(s) preceding ';'
    1>\spimpl.h(89): error C2873: 'copier_type' : symbol cannot be used in a using-declaration
    1>\spimpl.h(89): error C2143: syntax error : missing ';' before '='
    1>\spimpl.h(89): error C2238: unexpected token(s) preceding ';'
    1>\spimpl.h(90): error C2873: 'deleter_type' : symbol cannot be used in a using-declaration
    1>\spimpl.h(90): error C2143: syntax error : missing ';' before '='
    1>\spimpl.h(90): error C2238: unexpected token(s) preceding ';'
    1>\spimpl.h(91): error C2873: 'unique_ptr_type' : symbol cannot be used in a using-declaration
    1>\spimpl.h(91): error C2143: syntax error : missing ';' before '='
    1>\spimpl.h(91): error C2065: 'deleter_type' : undeclared identifier
    1>\spimpl.h(91): error C2923: 'std::unique_ptr' : 'deleter_type' is not a valid template type argument for parameter '_Dx'
    1>\spimpl.h(91): error C2238: unexpected token(s) preceding ';'
    1>\spimpl.h(92): error C2873: 'is_default_manageable' : symbol cannot be used in a using-declaration
    1>\spimpl.h(92): error C2143: syntax error : missing ';' before '='
    1>\spimpl.h(92): error C2238: unexpected token(s) preceding ';'
    1>\spimpl.h(101): error C2061: syntax error : identifier 'pointer'
    1>\spimpl.h(110): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(110): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(110): error C2653: 'is_default_manageable' : is not a class or namespace name
    1>\spimpl.h(110): error C2065: 'value' : undeclared identifier
    1>\spimpl.h(110): error C2975: '_Test' : invalid template argument for 'std::enable_if', expected compile-time constant expression
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>\spimpl.h(129): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(129): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(129): error C2653: 'is_default_manageable' : is not a class or namespace name
    1>\spimpl.h(129): error C2065: 'value' : undeclared identifier
    1>\spimpl.h(129): error C2975: '_Test' : invalid template argument for 'std::enable_if', expected compile-time constant expression
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>\spimpl.h(138): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(138): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(138): error C2653: 'is_default_manageable' : is not a class or namespace name
    1>\spimpl.h(138): error C2065: 'value' : undeclared identifier
    1>\spimpl.h(138): error C2975: '_Test' : invalid template argument for 'std::enable_if', expected compile-time constant expression
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>\spimpl.h(147): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(147): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(147): error C2065: 'deleter_type' : undeclared identifier
    1>\spimpl.h(147): error C2923: 'std::is_convertible' : 'deleter_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(147): error C2065: 'copier_type' : undeclared identifier
    1>\spimpl.h(147): error C2923: 'std::is_convertible' : 'copier_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(157): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(157): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(157): error C2065: 'deleter_type' : undeclared identifier
    1>\spimpl.h(157): error C2923: 'std::is_convertible' : 'deleter_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(157): error C2065: 'copier_type' : undeclared identifier
    1>\spimpl.h(157): error C2923: 'std::is_convertible' : 'copier_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(186): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(186): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(187): error C2065: 'deleter_type' : undeclared identifier
    1>\spimpl.h(187): error C2923: 'std::is_convertible' : 'deleter_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(188): error C2065: 'copier_type' : undeclared identifier
    1>\spimpl.h(188): error C2923: 'std::is_convertible' : 'copier_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(199): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(199): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(200): error C2065: 'deleter_type' : undeclared identifier
    1>\spimpl.h(200): error C2923: 'std::is_convertible' : 'deleter_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(201): error C2065: 'copier_type' : undeclared identifier
    1>\spimpl.h(201): error C2923: 'std::is_convertible' : 'copier_type' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(212): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(212): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(213): error C2653: 'is_default_manageable' : is not a class or namespace name
    1>\spimpl.h(213): error C2065: 'value' : undeclared identifier
    1>\spimpl.h(215): error C2975: '_Test' : invalid template argument for 'std::enable_if', expected compile-time constant expression
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>\spimpl.h(222): error C2065: 'pointer' : undeclared identifier
    1>\spimpl.h(222): error C2923: 'std::is_convertible' : 'pointer' is not a valid template type argument for parameter '_To'
    1>\spimpl.h(223): error C2653: 'is_default_manageable' : is not a class or namespace name
    1>\spimpl.h(223): error C2065: 'value' : undeclared identifier
    1>\spimpl.h(225): error C2975: '_Test' : invalid template argument for 'std::enable_if', expected compile-time constant expression
    1>          c:\program files\microsoft visual studio 11.0\vc\include\xtr1common(64) : see declaration of '_Test'
    1>\spimpl.h(239): error C2143: syntax error : missing ';' before '->'
    1>\spimpl.h(239): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    1>\spimpl.h(240): error C2146: syntax error : missing ';' before identifier 'get'
    1>\spimpl.h(240): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    1>\spimpl.h(240): warning C4183: 'get': missing return type; assumed to be a member function returning 'int'
    1>\spimpl.h(249): error C2146: syntax error : missing ';' before identifier 'release'
    1>\spimpl.h(249): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    1>\spimpl.h(249): warning C4183: 'release': missing return type; assumed to be a member function returning 'int'
    1>\spimpl.h(251): error C2146: syntax error : missing ';' before identifier 'release_unique'
    1>\spimpl.h(251): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    1>\spimpl.h(251): warning C4183: 'release_unique': missing return type; assumed to be a member function returning 'int'
    1>\spimpl.h(253): error C2071: 'spimpl::impl_ptr<T,Deleter,Copier>::operator bool' : illegal storage class
    1>\spimpl.h(255): error C2065: 'deleter_type' : undeclared identifier
    1>\spimpl.h(255): error C2923: 'std::remove_reference' : 'deleter_type' is not a valid template type argument for parameter '_Ty'
    1>\spimpl.h(256): error C2065: 'deleter_type' : undeclared identifier
    1>\spimpl.h(256): error C2923: 'std::remove_reference' : 'deleter_type' is not a valid template type argument for parameter '_Ty'
    1>\spimpl.h(258): error C2065: 'copier_type' : undeclared identifier
    1>\spimpl.h(258): error C2923: 'std::remove_reference' : 'copier_type' is not a valid template type argument for parameter '_Ty'
    1>\spimpl.h(259): error C2065: 'copier_type' : undeclared identifier
    1>\spimpl.h(259): error C2923: 'std::remove_reference' : 'copier_type' is not a valid template type argument for parameter '_Ty'
    1>\spimpl.h(263): error C2146: syntax error : missing ';' before identifier 'ptr_'
    1>\spimpl.h(263): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    1>\spimpl.h(264): error C2146: syntax error : missing ';' before identifier 'copier_'
    1>\spimpl.h(264): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    1>\spimpl.h(389): error C2332: 'class' : missing tag name
    1>\spimpl.h(389): error C2993: '' : illegal type for non-type template parameter '<unnamed-tag>'
    1>\spimpl.h(389): error C2143: syntax error : missing ',' before '...'
    1>\spimpl.h(79): error C2039: 'default_deleter_t' : is not a member of 'spimpl::details'
    1>\spimpl.h(79): error C2065: 'default_deleter_t' : undeclared identifier
    1>\spimpl.h(79): error C2974: 'spimpl::impl_ptr' : invalid template argument for 'Deleter', type expected
    1>          \spimpl.h(81) : see declaration of 'spimpl::impl_ptr'
    1>\spimpl.h(79): error C2039: 'default_copier_t' : is not a member of 'spimpl::details'
    1>\spimpl.h(79): error C2065: 'default_copier_t' : undeclared identifier
    1>\spimpl.h(79): error C2974: 'spimpl::impl_ptr' : invalid template argument for 'Copier', type expected
    1>          \spimpl.h(81) : see declaration of 'spimpl::impl_ptr'
    1>\spimpl.h(79): fatal error C1003: error count exceeds 100; stopping compilation
    1>  Generating Code...
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

how i can solve the problem?

**Comment by oliora** [comment]
I don't have VS2015 on hand right now. I'll install it and then come back, but this may take some time.

**Comment by oliora** [comment]
Closing as too old and definitely I don’t have an inspiration to fix it for such an old compiler
