### ISSUE TITLE
Equality operator (==) compares pointer or enveloped class

### ISSUE THREAD

**Issue by SteRoh** [oliora/samples#9]
Hi, 
i really like your smartpimpl implementation. 😄 

I wrote some Unittests for my library and i´m not sure if i have the right expectation for the operators.

```
    auto p1 = spimpl::make_unique_impl<int>(10);
    auto p2 = spimpl::make_unique_impl<int>(10);

    EXPECT_TRUE(p1 == p2); // that was my expectation
```

Is it just Pointer comparison or does it compare the enveloped Class?

https://godbolt.org/z/e5dWceEdo

**Comment by oliora** [comment]
Hey, it only compares the pointers not the values of enclosed impl.

**Comment by SteRoh** [comment]
Got it, thanks. 
You are right, my confusion comes from "too" smart.
Actually you tried to mimic of all the unique_ptr functions, i guess? 

My example with value type was just for simplification. :)

Great work anyway!

**Comment by oliora** [comment]
> Actually you tried to mimic of all the unique_ptr functions, i guess?

I weakly remember but I think you're right
